AllCops:
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - "db//**/*"

Style/ClassAndModuleChildren:
  Enabled: false
